run:
  fields:
    entity_id:
      example: "sensor.station_name"
    run_seconds:
      example: 60
    continue_running_stations:
      example: False
stop:
  fields:
    entity_id:
      example: "sensor.station_name"
set_water_level:
  fields:
    entity_id:
      example: "sensor.opensprinkler_water_level"
      required: true
      selector:
        entity:
          integration: opensprinkler
          domain: sensor
    water_level:
      example: 100
      required: true
      selector:
        number:
          min: 0
          max: 250
          mode: slider
          unit_of_measurement: "%"
set_rain_delay:
  fields:
    entity_id:
      example: "sensor.opensprinkler_rain_delay_stop_time"
      required: true
      selector:
        entity:
          integration: opensprinkler
          domain: sensor
    rain_delay:
      example: 24
      required: true
      selector:
        number:
          min: 0
          max: 32767
          mode: slider
          unit_of_measurement: "h"
pause_stations:
  fields:
    entity_id:
      example: "sensor.opensprinkler_pause_end_time"
      required: true
      selector:
        entity:
          integration: opensprinkler
          domain: sensor
    pause_duration:
      example: 600
      required: true
      selector:
        number:
          min: 0
          max: 86400
          mode: slider
          unit_of_measurement: "s"
reboot:
  fields:
    entity_id:
      example: "switch.opensprinkler_enabled"
